FromDoppler/Wordpress-Plugin-Doppler

- admin/partials/forms-edit.php
Se hizo rollback del disabled de inputs en la edición, solo de dejo la parte de doble optin ya que el servicio no permite hacer edición de esos campos
> dshop-149 readonly en edicion

- admin/js/doppler-form-admin.js
se agrego un disabled al input si se oculta para que no valide
> dshop-164 fix en campo de pagina de confirmacion

- admin/partials/forms-create.php
- admin/partials/forms-edit.php
se incrementó el maxlength del campo settings[form_pagina_confirmacion_url] a 150 como el otro campo url
> dshop-166 aumentar maxlength

- public/js/doppler-form-public.js
Se agregó al datepicker la propiedad yearRange que define del año actual hasta 100 años atras.
> dshop-165 rango de años

- doppler-form.php
- readme.txt
> New version of double opt-in

- doppler-form.php
- readme.txt
Upgrade version to include fix on error messages not showing when editing Double Opt-In forms.
> [DOI-724] Upgrade app version to 2.3.1

- readme.txt
Tested the plugin with the new wordpress version and works fine.
> Modify "Tested up to" value to version 6.1.0

- admin/controllers/Form_Controller.php
- includes/DopplerAPIClient/DopplerService.php
- public/doppler-forms-public.php
Se cambio la funcion wc_get_logger por un custom logger que genera los logs en la carpeta wp-content\uploads\logs
> fix logger

- doppler-form.php
- readme.txt
Publish new plugin version with the fix for the woocommerce logger function.
> [DOI-818] Update plugin version

- doppler-form.php
- readme.txt
Related to https://github.com/MakingSense/Wordpress-Plugin-Doppler/pull/50
> [DOI-837] Update plugin version to v2.3.3

- readme.txt
Wordpress released a new version and we reviewed the compatibility with our plugin.
> [DOI-897] Update "Tested up to" version on readme file

- admin/css/doppler-form-admin.css
- doppler-form.php
- readme.txt
The path was pointing to a custom path of our environment and obviously was breaking in the users servers.
> [DSHOP-187] Fix font's path

- admin/partials/forms-edit.php
- doppler-form.php
- readme.txt
@blancfabian este PR es para liberar una nueva version del plugin con el fix de los forms doble optin.
> [DOI-1168] Fix de error en forms doble optin y nueva version

- includes/helpers/Form_Helper.php
- public/js/doppler-form-public.js
Se fixeo bug al tener 2 fechas en un formulario solo una se podia editar debido a que se les estaba seteando un mismo id.
Ademas se ajusto el rango de fechas de -100 a +100 años, similar a forms en Doppler.
Se ajustaron los estilos en uno de los archivos.
> [DOI-461] Form fields format

- admin/doppler-admin.php
- admin/js/doppler-form-admin.js
- readme.txt
Este PR no esta muy relacionado a la tarea DOI-461, pero encontre un bug durante las pruebas de esa tarea.
Se habia modificado el orden de unos parametros de una funcion pero no las llamadas a dicha funcion por lo que me rompia al intentar ir a buscar las listas.
> [DOI-461] bug fixing

- readme.txt
El plugin es compatible con la ultima version de Wordpress
> [DOI-1132] Update tested up to version

- includes/helpers/Form_Helper.php
- public/js/doppler-form-public.js
When there are two or more forms on a same page it submits the fields for every form.
So I'm adding a form indicator to send only those inputs.
> [DOI-1198] Fix for double form submision

- includes/helpers/Form_Helper.php
- public/js/doppler-form-public.js
This will allow user to manually set the date. I also added a validation on blur
The place holder will be shown as dd/mm/yyyy, I already created a ticket to allow users to customize the placeholder.
> [DOI-1251] Add placeholder for date fields and allow to manualy set date

- admin/controllers/Form_Controller.php
- admin/js/doppler-form-admin.js
- admin/js/field-module.js
- includes/helpers/Form_Helper.php
I'm adding the input for placeholder edition on the create/edit form secction. To allow users set the placeholder they want.
> [DOI-1270] Add placeholder for date fields

- readme.txt
Update plugin to the up coming release of wordpress
> [DOW-6] Modify tested up to version 6.5

- admin/js/field-module.js
After my last changes to show the placeholder for date fields it seems I made a mistake and the date placeholder was showing in text fields too.
> [DOW-13] Show date placeholder only when field type is date

- includes/class-doppler-form-generator.php
- public/js/doppler-form-public.js
When adding more than 1 form from a short code the anidation was really messy and the forms where incluiding into one another.
This would make a strange behavior when submitting the form since it would take inputs from other forms.
With this change I'm isolating the forms. Also added a minor validation for phone input.
> [DOW-15] Fix forms anidation

- admin/js/field-module.js
This fixes an issue with [DOW-8](https://makingsense.atlassian.net/jira/software/projects/DOW/boards/196?selectedIssue=DOW-8)
[DOW-8]: https://makingsense.atlassian.net/browse/DOW-8?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOI-8] Remove empty lines when using type of multi options text

- public/css/doppler-form-public.css
The fields were overflowing out of the container on low resolutions. 
With these changes the inputs will be wrapped inside it.
> [DOW-16] Add responsive behavior to horizontal forms

- admin/js/doppler-form-admin.js
- admin/partials/forms-create.php
Fixes the default selection for some of the radio buttons.
Also fixes a weird UI behavior when selecting the radio buttons of "message confirmation" or "page confirmation".
> [DOW-22] Add default selection for radio buttons

- admin/doppler-admin.php
- admin/partials/data-hub.php
- admin/partials/doppler-forms-display.php
- admin/partials/lists-crud.php
- admin/partials/tabs-nav.php
> [DOW-32] Replace tabs for submenus

- admin/doppler-admin.php
- admin/js/doppler-styles.js
We should be carefull with this, since it might change our current styles.
For what I could test it's not currently afecting because we don't have the structure of classes expected by the style guide.
> [DOW-40] Add doppler styles

- admin/css/doppler-form-admin.css
- admin/js/doppler-form-admin.js
- admin/partials/forms-list.php
> [DOW-56] Add copy shortcode icon

- admin/css/doppler-form-admin.css
- doppler-form.php
- readme.txt
Users reported an issue in the plugin seccion where checkbox inputs couldn't be checked.
> [DOI-1652] fix styles conflict

- includes/class-doppler-form-generator.php
- includes/helpers/Form_Helper.php
- public/css/doppler-form-public.css
- public/css/doppler-form-public.scss
- public/js/doppler-form-public.js
- public/scss/doppler-form-public.scss
This fixes two issues with elementor popups.
First, sometimes it would break the popup rendering and making the page reload on an infite loop.
Second, the form submit wasn't being triggered.
There is still an issue pending when we display the datepicker if you click on it the popup closes.
I will keep working on it.
Also I still need to test the new code.
Easyer review commit by commit.
> [DOW-63] Fix dplr forms in elementor popup

- includes/class-doppler-form.php
- includes/models/Base_Model.php
- includes/models/Form_Model.php
This new table will be used to track the form's events.
> [DOW-72] Add new form events table

- doppler-form.php
- includes/class-doppler-form-widget.php
- readme.txt
On the last release I forgot to test the form's widgets.
A user complained about forms not rendering.
> DOW-75 Fix form rendering when displayed as widget

- includes/models/Base_Model.php
I don't know what happened here... 😬
> [DOW-82] fix variable name

- admin/partials/api-connection.php
> [DOW-85] Fix Woocommerce KPI in dashboard

- admin/doppler-admin.php
- admin/partials/api-connection.php
This is for handling when the value gets to big. It will replace thousands by K, millions by M and billions by B.
> [DOW-86] Sanitize KPI values in dashboard

- admin/partials/api-connection.php
After latest changes I missed this parenthesis and the calculus counting only the first value
> Fix woocommerce kpi

- admin/doppler-admin.php
- admin/partials/settings.php
Refactored the validation regex and also added a validation on the content
> [DOW-92] Fix vulnerability on tracking script setting

- admin/js/doppler-form-admin.js
Most of the changes it's just from reverting a previous commit, lots of indentations changes.
The main change it's just setting the window on load function outside the document ready.
> [DOW-96] Fix loading screen not hiding sometimes

- admin/js/doppler-form-admin.js
With the previous approach the billboard chart was looking funny.
> [DOW-96] Hide loading on document ready

- admin/css/doppler-form-admin.css
- admin/doppler-admin.php
- admin/js/doppler-form-admin.js
- admin/partials/api-connection.php
- includes/helpers/Form_Helper.php
Most of the changes are from reverting latest commits, since I need to realease a new version and I don't want to include those yet.
The root of the bug was a code conflict incorrectly solved a few commits ago.
> [DOW-112] Fix bug on form render

- doppler-form.php
- readme.txt
> Release version 2.5.1
